<?php

/**
 * @file
 * Reorder #title, #description and #children in forms.
 *
 * Introduces a new Form API attribute: #description_display. Its value can be
 * either 'before' or 'after', relative to #children, or the actual input
 * element. It behaves much like the D8 issue with the same purpose.
 * @see https://www.drupal.org/node/314385
 *
 * The combination of #description_display and #title_display together makes the
 * ordering of element attributes more complex, and in cases where both #title
 * and #description are on the same side of #children, #title always comes
 * first.
 */

/**
 * Implements hook_theme().
 */
function fel_theme($existing, $type, $theme, $path) {
  return array(
    'fel_form_element' => array(
      'render element' => 'element',
    ),
    'fel_text_format_wrapper' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Implements hook_element_info_alter().
 */
function fel_element_info_alter(&$elements) {
  // Replace all #theme_wrapper[] = 'form_element' with our custom form_element
  // theme.
  $form_element_wrappers = array(
    // Core.
    'textfield',
    'machine_name',
    'password',
    'password_confirm',
    'textarea',
    'radio',
    'checkbox',
    'select',
    'date',
    'file',
    'item',
    'managed_file',
    // Contrib.
    'link_field',
    'media',
    'mfw_managed_file',
  );
  foreach ($form_element_wrappers as $type) {
    if (!empty($elements[$type])) {
      fel_wrapper_replace('form_element', 'fel_form_element', $elements[$type]);
    }
  }
  // 'radios' and 'checkboxes' are special.
  $elements['checkboxes']['#pre_render'][] = 'fel_options_pre_render';
  $elements['radios']['#pre_render'][] = 'fel_options_pre_render';

  // 'text_format': Replace #theme_wrapper with our own and reshuffle the title,
  // description and element trio.
  if (!empty($elements['text_format']) and module_exists('filter')) {
    fel_wrapper_replace('text_format_wrapper', 'fel_text_format_wrapper', $elements['text_format']);
    $elements['text_format']['#process'][] = 'fel_filter_process_format';
  }
}

/**
 * Replace #theme_wrapper => 'form_element' with our own.
 */
function fel_options_pre_render($element) {
  fel_wrapper_replace('form_element', 'fel_form_element', $element);
  return $element;
}

/**
 * Extra processing for 'text_format' elements.
 *
 * Filter module groups the title and the form element (#title, #children) into
 * the 'value' child of '#type' == 'text_format' element and renders the
 * '#description' item outside this, so there is no way to jam #description
 * between #title and #children.
 *
 * This processing is necessary in order to move the description from this
 * element to the child element 'value' when '#description_display' == 'before.
 */
function fel_filter_process_format($element) {
  if (!empty($element['#description']) and !empty($element['#description_display']) and $element['#description_display'] == 'before') {
    $element['value']['#description'] = $element['#description'];
    unset($element['#description']);
  }
  return $element;
}

/**
 * Replacement theme for 'form_element'.
 *
 * @see theme_form_element()
 */
function theme_fel_form_element($variables) {
  $element = &$variables['element'];

  // This function is invoked as theme wrapper, but the rendered form element
  // may not necessarily have been processed by form_builder().
  $element += array(
    '#title_display' => 'before',
  );

  // Add element #id for #type 'item'.
  if (isset($element['#markup']) && !empty($element['#id'])) {
    $attributes['id'] = $element['#id'];
  }
  // Add element's #type and #name as class to aid with JS/CSS selectors.
  $attributes['class'] = array('form-item');
  if (!empty($element['#type'])) {
    $attributes['class'][] = 'form-type-' . strtr($element['#type'], '_', '-');
  }
  if (!empty($element['#name'])) {
    $replacements = array(' ' => '-', '_' => '-', '[' => '-', ']' => '');
    $attributes['class'][] = 'form-item-' . strtr($element['#name'], $replacements);
  }
  // Add a class for disabled elements to facilitate cross-browser styling.
  if (!empty($element['#attributes']['disabled'])) {
    $attributes['class'][] = 'form-disabled';
  }
  $output = '<div' . drupal_attributes($attributes) . '>' . "\n";

  // If #title is not set, we don't display any label or required marker.
  if (!isset($element['#title'])) {
    $element['#title_display'] = 'none';
  }
  $prefix = isset($element['#field_prefix']) ? '<span class="field-prefix">' . $element['#field_prefix'] . '</span> ' : '';
  $suffix = isset($element['#field_suffix']) ? ' <span class="field-suffix">' . $element['#field_suffix'] . '</span>' : '';

  $element_parts = array('children' => $prefix . $element['#children'] . $suffix);
  if ($element['#title_display'] != 'none' and $element['#title_display'] != 'attribute') {
    $element_parts['title'] = theme('form_element_label', $variables);
  }
  if (!empty($element['#description'])) {
    $element_parts['description'] = '<div class="description">' . $element['#description'] . "</div>\n";
  }
  fel_order_output($element, $element_parts);
  $output .= implode(' ', $element_parts);
  $output .= "\n</div>\n";

  return $output;
}

/**
 * Replacement theme for 'text_format'.
 *
 * @see theme_text_format_wrapper()
 */
function theme_fel_text_format_wrapper($variables) {
  $element = $variables['element'];

  $parts['children'] = $element['#children'];
  if (!empty($element['#description'])) {
    $parts['description'] = '<div class="description">' . $element['#description'] . '</div>';
  }
  $output = '<div class="text-format-wrapper">';
  $output .= fel_order_output($element, $parts);
  $output .= "</div>\n";

  return $output;
}

/**
 * Replace $search in $element['#theme_wrapper'] with $replace.
 *
 * @param string $search
 *   The theme name to search for.
 * @param string $replace
 *   Replacement theme name.
 * @param array $element
 *   The element to search in.
 */
function fel_wrapper_replace($search, $replace, array &$element) {
  if (is_array($element['#theme_wrappers'])) {
    $key = array_search($search, $element['#theme_wrappers']);
    if ($key !== FALSE) {
      unset($element['#theme_wrappers'][$key]);
      $element['#theme_wrappers'][] = $replace;
    }
  }
}

/**
 * Determine the render order of a form element.
 *
 * Returns what order #title, #children and #description should be rendered in,
 * based on #title_display and #description_display.
 *
 * @param array $element
 *   Form element.
 *
 * @return array
 *   An array with the three values 'title', 'children' and 'description' in
 *   various orders.
 */
function fel_get_order(array $element) {
  if (!empty($element['#element_order'])) {
    return $element['#element_order'];
  }

  $title_before = (empty($element['#title_display']) or $element['#title_display'] == 'before' or $element['#title_display'] == 'invisible');
  $description_before = (empty($element['#description_display']) ? FALSE : ($element['#description_display'] == 'before'));

  if ($title_before) {
    $order = $description_before ? array('title', 'description', 'children') : array('title', 'children', 'description');
  }
  else {
    $order = $description_before ? array('description', 'children', 'title') : array('children', 'title', 'description');
  }
  return $order;
}

/**
 * Return the output of $parts in configured order.
 *
 * @param array $element
 *   A form element.
 * @param array $parts
 *   An associative array with the following optional keys:
 *     - 'title'.
 *     - 'description'.
 *     - 'children'.
 *
 * @return string
 *   The items in order according to configuration in $element.
 */
function fel_order_output(array $element, array &$parts) {
  $element_order = fel_get_order($element);
  $parts_ordered = array();
  $out = '';
  foreach ($element_order as $element_item) {
    if (!empty($parts[$element_item])) {
      $out .= $parts[$element_item];
      $parts_ordered[$element_item] = $parts[$element_item];
    }
  }
  $parts = $parts_ordered;
  return $out;
}
